config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  resources :practices
  resources :daily_progresses, only: [:new, :create]

end

app/models/daily_progress.rb
# ## Schema Information
#
# Table name: `daily_progresses`
#
# ### Columns
#
# Name               | Type               | Attributes
# ------------------ | ------------------ | ---------------------------
# **`id`**           | `integer`          | `not null, primary key`
# **`practice_id`**  | `integer`          |
# **`done_at`**      | `date`             |
# **`goal`**         | `integer`          | `not null`
# **`progress`**     | `integer`          |
# **`created_at`**   | `datetime`         | `not null`
# **`updated_at`**   | `datetime`         | `not null`
#

class DailyProgress < ActiveRecord::Base
  belongs_to :practice
  validates  :practice,    presence: true
  validates  :done_at,     presence: true
  validates  :progress,    numericality: true

  after_initialize :set_goal

  private
  def set_goal
    self.goal = DailyProgress.select(:progress).where(done_at: Time.zone.yesterday, practice_id: practice_id).pluck(:progress).first || 0
  end
end

app/models/practice.rb
# ## Schema Information
#
# Table name: `practices`
#
# ### Columns
#
# Name              | Type               | Attributes
# ----------------- | ------------------ | ---------------------------
# **`id`**          | `integer`          | `not null, primary key`
# **`user_id`**     | `integer`          |
# **`title`**       | `string`           |
# **`unit`**        | `string`           |
# **`created_at`**  | `datetime`         | `not null`
# **`updated_at`**  | `datetime`         | `not null`
#

class Practice < ActiveRecord::Base
  belongs_to :user
  has_many   :daily_progresses
  validates  :user,    presence: true
  validates  :title,   presence: true, length: { maximum: 50 }
  validates  :unit,    presence: true, length: { maximum: 10 }
end

app/models/range_progresses.rb
class RangeProgresses
  def initialize(id, start_date, end_date)
    @start_date = start_date
    @end_date = end_date
    @progresses = DailyProgress.where(practice_id: id, done_at: start_date..end_date)
    @done_dates = @progresses.where('progress > 0').pluck(:done_at).sort
  end

  def format_each_week
    (@start_date..@end_date).each_with_object([]) do |date, formated_dates|
      if formated_dates.blank? || formated_dates[-1].last.wday == 6
        formated_dates << [date]
      else
        formated_dates[-1] << date
      end
    end
  end

  def total_done
    @done_dates.count
  end

  def longest_streak
    return @longest if defined? @longest

    dates_by_continuity = \
      @done_dates.each_with_object([]) do |date, dates_by_continuity|
        if dates_by_continuity.blank? || dates_by_continuity.last.last + 1.day != date
          dates_by_continuity << [date]
        else
          dates_by_continuity.last << date
        end
      end
    longest = dates_by_continuity.max_by{|dates| dates.count}
    @longest = {
      days: longest.count,
      start_date: longest[0],
      end_date: longest[-1]
    }
  end

  def current_streak
    return @current if defined? @current

    dates_from_current = @done_dates.reverse
    # FIXME: DuplicateMethodCall dates_from_current[0]
    if dates_from_current[0] == Time.zone.today
      streak = 1
      start_date = dates_from_current[0]
      while dates_from_current[0] - 1.day == dates_from_current[1]
        dates_from_current = dates_from_current.drop(1)
        start_date = dates_from_current[0]
        streak += 1
      end
    else
      streak, start_date = 0, "now, let's start!"
    end
    @current = {
      days: streak,
      start_date: start_date
    }
  end

  def progress_rate(date)
    daily = @progresses.to_a.select{|daily| daily.done_at == date}.first
    return 0 if daily.blank?
    daily.progress.to_f / daily.goal.to_f
  end
end

app/models/user.rb
# ## Schema Information
#
# Table name: `users`
#
# ### Columns
#
# Name              | Type               | Attributes
# ----------------- | ------------------ | ---------------------------
# **`id`**          | `integer`          | `not null, primary key`
# **`name`**        | `string`           |
# **`provider`**    | `string`           |
# **`uid`**         | `string`           |
# **`image`**       | `string`           |
# **`created_at`**  | `datetime`         | `not null`
# **`updated_at`**  | `datetime`         | `not null`
#

class User < ActiveRecord::Base
  has_many :practices
  validates :name,     presence: true
  validates :provider, presence: true
  validates :uid,      presence: true, uniqueness: true
  validates :image,    presence: true, uniqueness: true

  def self.find_or_create_from_auth_hash(auth)
    User.find_or_create_by(provider: auth[:provider], uid: auth[:uid]) do |user|
      user.name = auth[:info][:nickname]
      user.image = auth[:info][:image]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end
end

app/controllers/daily_progresses_controller.rb
class DailyProgressesController < ApplicationController
  permits :progress, :practice_id, :goal

  def new(practice_id:)
    @daily_progress = DailyProgress.new practice_id: practice_id
    render json: @daily_progress, status: 201
  end

  def create(daily_progress)
    @daily_progress = DailyProgress.new daily_progress
    @daily_progress.done_at = Time.zone.today
    if @daily_progress.save
      render json: @daily_progress, status: 201, notice: '更新しました'
    else
      render json: { errors: @daily_progress.errors.full_messages }, status: 422
    end
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  permits :title, :unit

  def index
    @practices = current_user.practices
  end

  def show
    @practice = Practice.find(params[:id])
    @end_date = Time.zone.now.to_date
    @start_date = @end_date.years_ago(1).to_date
    @range_progresses = RangeProgresses.new(params[:id], @start_date, @end_date)
  end

  def new
    @practice = Practice.new
  end

  def create(practice)
    @practice = Practice.new(practice).tap { |p| p.user = current_user }
    if @practice.save
      redirect_to :root, notice: '習慣を登録しました'
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action -> { request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:twitter] } unless Twitter.login?

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to :root
  end

  private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    redirect_to practices_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in_url
    Twitter.login? ? 'auth/twitter' : '/auth/developer'
  end
end

app/helpers/practice_helper.rb
module PracticeHelper
  # TODO: 使ってみて緑の濃さ調整する
  def color(progress_rate)
    if progress_rate > 1
      '#1e6823'
    elsif progress_rate == 1
      '#44a340'
    elsif progress_rate > 0.5
      '#8cc665'
    elsif progress_rate > 0
      '#d6e685'
    else
      '#eee'
    end
  end
end

app/views/daily_progresses/_index.html.slim
svg
  g transform='translate(20, 20)'
    - @display_dates.each_with_index do |w, i|
      g transform="translate(#{i * 13}, 0)"
        - w.each do |d|
          rect width='11' height='11' y="#{d.wday * 13}" fill='#eeeeee'
    text text-anchor='middle' dx='-10' dy='22'
      | M
    text text-anchor='middle' dx='-10' dy='48'
      | W
    text text-anchor='middle' dx='-10' dy='74'
      | F

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[http-equiv="content-type" content="text/html; charset=UTF-8"]
    meta[charset="utf-8"]
    title
      | Shibaph
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  body
    = render 'shared/header'
    .container
      = yield
    = render 'shared/footer'

app/views/practices/_daily_progresses.html.slim
svg
  g transform='translate(20, 20)'
    - @range_progresses.format_each_week.each_with_index do |week, i|
      g transform="translate(#{i * 13}, 0)"
        - week.each do |day|
          rect width='11' height='11' y="#{day.wday * 13}" fill="#{color(@range_progresses.progress_rate(day))}"
    text text-anchor='middle' dx='-10' dy='22'
      | M
    text text-anchor='middle' dx='-10' dy='48'
      | W
    text text-anchor='middle' dx='-10' dy='74'
      | F

app/views/practices/_form.html.slim
= form_for practice do |f|
  - if practice.errors.any?
    ul.bg-danger
      - practice.errors.full_messages.each do |message|
        li
          = message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', maxlength: 50
  .form-group
    = f.label :unit
    = f.text_field :unit, class: 'form-control', maxlength: 10
  = f.button 'Submit', class: 'btn btn-default'

app/views/practices/index.html.slim
.profile.row
- if @practices.present?
  ul.practices-list.col-md-12
    - @practices.each do |practice|
      li.practice.row
        .title.col-xs-9
          i.fa.fa-check-square-o.fa-2x
          .text
            label= link_to practice.title, practice_path(practice.id)
        .text.col-xs-3
          =link_to '進捗入力', new_daily_progress_path(practice_id: practice.id), data: {toggle: 'modal', target: '#newProgress'}, remote: true, id: "newDailyProgress-#{practice.id}"

- else
  .no-practice
    | まだ習慣が登録されていません

= form_for DailyProgress.new do |f|
  #newProgress.modal.fade aria-labelledby="newProgressLabel" role="dialog" tabindex="-1"
    .modal-dialog role="document"
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
          h4#newProgressLabel.modal-title 進捗入力
        .modal-body
          .form-group
            = f.label :goal
            = f.text_field :goal, class: 'form-control'
          .form-group
            = f.label :progress
            = f.text_field :progress, class: 'form-control'
          = f.hidden_field :practice_id
        .modal-footer
          = f.button "閉じる", data: { dismiss: 'modal' }, class: 'btn btn-default'
          = f.submit "登録", data: { dismiss: 'modal' }, class: 'btn btn-primary'

app/views/practices/new.html.slim
h1 Practices#new

= render 'form', practice: @practice

= link_to 'Back', root_path

app/views/practices/show.html.slim
.practice
  .title.col-xs-12
    i.fa.fa-check-square-o.fa-2x
    .text
      h3 = @practice.title
  .daily-progress.col-xs-12
    = render partial: 'daily_progresses'
  .analysis-box.col-xs-12.col-md-4
    .text-muted.col-md-12
      | Total done in this year
    .count.col-md-12
      = "#{@range_progresses.total_done} days"
    .text-muted.col-md-12
      = "#{@start_date} - #{@end_date}"
  .analysis-box.col-xs-12.col-md-4
    .text-muted.col-md-12
      | Longest streak
    .count.col-md-12
      = "#{@range_progresses.longest_streak[:days]} days"
    .text-muted.col-md-12
      = "#{@range_progresses.longest_streak[:start_date]} - #{@range_progresses.longest_streak[:end_date]}"
  .analysis-box.col-xs-12.col-md-4
    .text-muted.col-md-12
      | Current streak
    .count.col-md-12
      = "#{@range_progresses.current_streak[:days]} days"
    .text-muted.col-md-12
      = "From #{@range_progresses.current_streak[:start_date]}"

app/views/shared/_footer.html.slim
.footer
  .container
    p.text-muted
      | Maintained by highwide & ta1kt0me. © 2015 All rights reserved.

app/views/shared/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.icon-bar
        span.icon-bar
      = link_to 'Shibaph', root_path, {class: "navbar-brand"}
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li.hidden-xs
            = link_to new_practice_path do
              i.glyphicon.glyphicon-plus.white
          li.visible-xs-inline
            = link_to 'New Practice', new_practice_path
          li.navbar-right__profile.hidden-xs
            = link_to '#' do
              = image_tag(current_user.image, class: 'img-rounded', size: '32x32')
          li.navbar-right__profile.visible-xs-inline
            = link_to '#'
              = image_tag(current_user.image, class: 'img-rounded', size: '32x32')
              = current_user.name
        - else
          li
            = link_to 'Sign Up / Sign In with Twitter', sign_in_url

app/views/top/index.html.slim
h1 Top#index

- if flash[:notice]
  p.bg-success
    = flash[:notice]

p Find me in app/views/top/index.html.slim